/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package internetdownloadmanager;

import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.BufferedInputStream;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.channels.Channels;
import java.nio.channels.ReadableByteChannel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author zamalek
 */
public class InternetDownloadManger extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form InternetDownloadManger
     */
    UDModel i = new UDModel();
    DBInternetDown db = new DBInternetDown();
    ModelInternetDown M = new ModelInternetDown();
    public static String[] app20 =  new String[]{"File Name" , "Size" , "URL" , "Directory" , "Date"};
      

    public InternetDownloadManger() {
        initComponents();
        ImageIcon img = new ImageIcon("src\\icon\\Main_Panal\\App-Control-Panel-icon.png");
        this.setIconImage(img.getImage());
        jXHyperlink2.setVisible(false);
        jXHyperlink3.setVisible(false);
        jXHyperlink4.setVisible(false);
        panelGlass2.setVisible(false);
        setLocation(150, 100);
        setSize(977, 590);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jXHyperlink1 = new org.jdesktop.swingx.JXHyperlink();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jXHyperlink8 = new org.jdesktop.swingx.JXHyperlink();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panelGlass3 = new usu.widget.glass.PanelGlass();
        jXHyperlink2 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink3 = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlink4 = new org.jdesktop.swingx.JXHyperlink();
        jLabel6 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        jXHyperlink5 = new org.jdesktop.swingx.JXHyperlink();
        jLabel5 = new javax.swing.JLabel();
        panelGlass6 = new usu.widget.glass.PanelGlass();
        jXHyperlink7 = new org.jdesktop.swingx.JXHyperlink();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        jXHyperlink6 = new org.jdesktop.swingx.JXHyperlink();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Sakkal Majalla", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("URL");

        jLabel4.setBackground(new java.awt.Color(153, 255, 0));
        jLabel4.setFont(new java.awt.Font("Sakkal Majalla", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Just  paste URL Here");

        jXHyperlink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/Untitled.png"))); // NOI18N
        jXHyperlink1.setText("");
        jXHyperlink1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/m.gif"))); // NOI18N
        jXHyperlink1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NAME");

        jLabel11.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SIZE");

        jLabel12.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status");

        jLabel13.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Progress");

        jLabel14.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("URL");

        jLabel15.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Remaining Time");

        jLabel16.setFont(new java.awt.Font("Sakkal Majalla", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Directory");

        jLabel9.setFont(new java.awt.Font("Sakkal Majalla", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel17.setFont(new java.awt.Font("Sakkal Majalla", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel18.setFont(new java.awt.Font("Sakkal Majalla", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel19.setFont(new java.awt.Font("Sakkal Majalla", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel20.setFont(new java.awt.Font("Sakkal Majalla", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel21.setFont(new java.awt.Font("Sakkal Majalla", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(86, 86, 86)
                        .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(96, 96, 96)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGlass2Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelGlass1Layout = new javax.swing.GroupLayout(panelGlass1);
        panelGlass1.setLayout(panelGlass1Layout);
        panelGlass1Layout.setHorizontalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGlass1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGlass1Layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelGlass1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jXHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGlass1Layout.setVerticalGroup(
            panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(panelGlass1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(panelGlass1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jXHyperlink1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelGlass1);
        panelGlass1.setBounds(20, 60, 900, 440);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/xd.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 970, 520);

        jXHyperlink8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/print.png"))); // NOI18N
        jXHyperlink8.setText("");
        jXHyperlink8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/print (1).png"))); // NOI18N
        jXHyperlink8.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/print (1).png"))); // NOI18N
        jXHyperlink8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink8ActionPerformed(evt);
            }
        });
        jPanel1.add(jXHyperlink8);
        jXHyperlink8.setBounds(1620, 330, 40, 40);

        jTable1.setFont(new java.awt.Font("Sakkal Majalla", 1, 17)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "File Name", "Size", "Status", "Description"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(1, 5));
        jTable1.setRowHeight(25);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(970, 0, 710, 320);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/xd.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(750, 0, 940, 530);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(null);

        panelGlass3.setBackground(new java.awt.Color(204, 204, 0));
        panelGlass3.setForeground(new java.awt.Color(255, 255, 0));

        jXHyperlink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/play.png"))); // NOI18N
        jXHyperlink2.setText("");
        jXHyperlink2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/play_hot.png"))); // NOI18N
        jXHyperlink2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/play_hot.png"))); // NOI18N

        jXHyperlink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/pause.png"))); // NOI18N
        jXHyperlink3.setText("");
        jXHyperlink3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/pause_hot.png"))); // NOI18N

        jXHyperlink4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/audio-video-outline-stop-48.png"))); // NOI18N
        jXHyperlink4.setText("");
        jXHyperlink4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/button-stop_basic_green.png"))); // NOI18N

        javax.swing.GroupLayout panelGlass3Layout = new javax.swing.GroupLayout(panelGlass3);
        panelGlass3.setLayout(panelGlass3Layout);
        panelGlass3Layout.setHorizontalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXHyperlink2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jXHyperlink3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXHyperlink4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelGlass3Layout.setVerticalGroup(
            panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass3Layout.createSequentialGroup()
                .addGroup(panelGlass3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jXHyperlink2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXHyperlink3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXHyperlink4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(panelGlass3);
        panelGlass3.setBounds(780, 0, 220, 50);

        jLabel6.setFont(new java.awt.Font("Sakkal Majalla", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("ME");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 0, 50, 50);

        jXHyperlink5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/home-32.png"))); // NOI18N
        jXHyperlink5.setText("");
        jXHyperlink5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass4Layout = new javax.swing.GroupLayout(panelGlass4);
        panelGlass4.setLayout(panelGlass4Layout);
        panelGlass4Layout.setHorizontalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jXHyperlink5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        panelGlass4Layout.setVerticalGroup(
            panelGlass4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jXHyperlink5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPanel2.add(panelGlass4);
        panelGlass4.setBounds(310, -28, 60, 110);

        jLabel5.setFont(new java.awt.Font("Sakkal Majalla", 1, 32)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Down");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 0, 63, 50);

        jXHyperlink7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/700015-icon-27-one-finger-click-32.png"))); // NOI18N
        jXHyperlink7.setText("");
        jXHyperlink7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/699458-icon-27-one-finger-click-32.png"))); // NOI18N

        javax.swing.GroupLayout panelGlass6Layout = new javax.swing.GroupLayout(panelGlass6);
        panelGlass6.setLayout(panelGlass6Layout);
        panelGlass6Layout.setHorizontalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXHyperlink7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGlass6Layout.setVerticalGroup(
            panelGlass6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jXHyperlink7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel2.add(panelGlass6);
        panelGlass6.setBounds(540, -20, 60, 100);

        jXHyperlink6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/JAVA.png"))); // NOI18N
        jXHyperlink6.setText("");
        jXHyperlink6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlink6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGlass5Layout = new javax.swing.GroupLayout(panelGlass5);
        panelGlass5.setLayout(panelGlass5Layout);
        panelGlass5Layout.setHorizontalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXHyperlink6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelGlass5Layout.setVerticalGroup(
            panelGlass5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGlass5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jXHyperlink6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel2.add(panelGlass5);
        panelGlass5.setBounds(420, -20, 60, 90);

        jLabel2.setFont(new java.awt.Font("Sakkal Majalla", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("URL-");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 52, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/software/engineering/icons/header.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(0, 0, 970, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1696, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXHyperlink1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink1ActionPerformed
        if (jTextField1.getText().equals("")) {;
            JOptionPane.showMessageDialog(null, "Error , you should fill URL field");
        } else {

            try {
                i.setURL(jTextField1.getText());
                jXHyperlink2.setVisible(true);
                jXHyperlink3.setVisible(true);
                jXHyperlink4.setVisible(true);
                 BufferedImage img = null;
       
//        int x = 10;
//
//        int y = 10;
//        Image dimg = img.getScaledInstance(x, y, 10);

//                 int delay = 60 / 1555;
//                new Timer(delay, new ActionListener() {
//                    int x = 20;
//                    int y = 0;
//
//                    @Override
//                    public void actionPerformed(ActionEvent e) {
//                        int maxX = jPanel1.getWidth();
//                        int maxY = jPanel1.getHeight();
//                        if (x > -735) {
//                            x--;
//                            //  y++;
//                            jPanel1.setLocation(x, (int) jPanel1.getLocation().getY());
//
//                        } else {
         panelGlass2.setVisible(true);
         down();
       
                            
                            
//                            panelGlass2.setVisible(true);
//                            try {
//                                BufferedWriter br = new BufferedWriter(new FileWriter("A:\\Software Engineering\\RTC System IT.U\\src\\filles\\EmpSett.txt"));
//                                br.write(jTextField1.getText());
//
//                                br.close();
//v
//                            } catch (Exception ee) {
//                            }
//                            new Director(null, rootPaneCheckingEnabled).setVisible(true);
//                            ((Timer) e.getSource()).stop();
//
//                        }
//                    }
//                }).start();
                down();


            } catch (Exception r) {
            }

       
        }

    }//GEN-LAST:event_jXHyperlink1ActionPerformed

    private void jXHyperlink6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink6ActionPerformed
     
      jXHyperlink6.setEnabled(false);
      jXHyperlink5.setEnabled(true);
      Thread thread = new Thread(new Runnable() {
          int x=0;             
          @Override
                        public void run() {
              int c =0;
              while(c<700){
                            if (x > -690) {
                                try {
                                    x--;
                                    //  y++;
                                    jPanel1.setLocation(x, (int) jPanel1.getLocation().getY());
                                 Thread.sleep(1);
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(InternetDownloadManger.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            } else {
                             
                            }
                            c++;
                        } 
          }
                    
      });
      thread.start();
     try {
         

            M.setFilename(null);
            Object d[][] = db.Get_Downs();
            DefaultTableModel All_Downs = new DefaultTableModel(d, app20);
            jTable1.setModel(All_Downs);
        } catch (ClassNotFoundException ex) {
        } catch (SQLException ex) {
        }   
          
    }//GEN-LAST:event_jXHyperlink6ActionPerformed

    private void jXHyperlink5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink5ActionPerformed
     /*  int delay = 60 / 1555;
                new Timer(delay, new ActionListener() {
                    int x = -706;
                    int y = 0;

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int maxX = jPanel1.getWidth();
                        int maxY = jPanel1.getHeight();
                        if (x <0) {
                            x++;
                            //  y++;
                            jPanel1.setLocation(x, (int) jPanel1.getLocation().getY());

                        } else {
//
//         down();
//        panelGlass2.setVisible(true);
//                            
                            
                            ((Timer) e.getSource()).stop();

                        }
                    }
                }).start();
               
*/

           jXHyperlink6.setEnabled(true); 
           jXHyperlink5.setEnabled(false);
   Thread thread = new Thread(new Runnable() {
          int x=-690;             
          @Override
                        public void run() {
              int c =0;
              while(c<700){
                            if (x < 0) {
                             
                                    x++;
                                    //  y++;
                                    jPanel1.setLocation(x, (int) jPanel1.getLocation().getY());
                                try {
                                    Thread.sleep(1);
                                } catch (InterruptedException ex) {
                                    Logger.getLogger(InternetDownloadManger.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            
                            }   
                             else {
                             
                            }
                            c++;
                        } 
          }
            
      });
      thread.start();      
    
    }//GEN-LAST:event_jXHyperlink5ActionPerformed

    private void jXHyperlink8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlink8ActionPerformed
        try {     
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/reg", "root", "");
            JasperReport c = JasperCompileManager.compileReport("src\\software\\engineering\\report\\report1.jrxml");


            JasperPrint print = JasperFillManager.fillReport(c, null, conn);
            JasperViewer.viewReport(print, false);
        } catch (JRException ex) {
            System.out.println(ex.getMessage());
        } catch (SQLException ex) {
          System.out.println(ex.getMessage());
        } catch (ClassNotFoundException ex) {
            System.out.println(ex.getMessage());
        }
        

    }//GEN-LAST:event_jXHyperlink8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        InternetDownloadManger x = new InternetDownloadManger();
          //Thread c= new Thread(x);
        x.setVisible(true);
        //  c.start();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InternetDownloadManger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InternetDownloadManger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InternetDownloadManger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InternetDownloadManger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InternetDownloadManger().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public static javax.swing.JLabel jLabel17;
    public static javax.swing.JLabel jLabel18;
    public static javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel20;
    public static javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTextField jTextField1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink1;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink2;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink3;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink4;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink5;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink6;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink7;
    private org.jdesktop.swingx.JXHyperlink jXHyperlink8;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass3;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass6;
    // End of variables declaration//GEN-END:variables

    public void down() {

        try {

            BufferedWriter br = new BufferedWriter(new FileWriter("A:\\Software Engineering\\RTC System IT.U\\src\\filles\\EmpSett.txt"));

            Long start = System.nanoTime();
// do your read

            System.out.println(start);

            String U = jTextField1.getText();
            if (!U.contains("http")) {
                U = "http://" + U;

            }
            System.out.println(U);
            URL website = new URL(U);
            InputStream file_len = website.openConnection().getInputStream();
            System.out.println("fff" + file_len);
            long file_length = website.openConnection().getContentLength();

            if (file_length < 0) {
                System.out.println("Size of " + website.getFile() + ": " + file_length + "\nSomething wrong with your url or connection? Couldn't download it!");
                System.exit(1);
            } else {
                System.out.println("Size of " + website.getFile() + ": " + file_length / 1024 + "KByte");
                jLabel18.setText(file_length / 1024 + "KByte");
            }
            String fileName = U.substring(U.lastIndexOf("/") + 1);
            jLabel20.setText(U);
            System.out.println("C:\\Users\\zamalek\\Desktop\\" + fileName);
            jLabel9.setText(fileName);
            ReadableByteChannel rbc = Channels.newChannel(website.openStream());
            FileOutputStream fos = new FileOutputStream("C:\\Users\\zamalek\\Desktop\\" + fileName);
            jLabel21.setText("C:/Users/zamalekDesktop/");
            fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
            Long end = System.nanoTime() / 1000000000;

            ///////////////////////////


            float fileSize = Float.parseFloat(website.openConnection().getHeaderField("Content-Length"));

           BufferedInputStream in = new BufferedInputStream(website.openConnection().getInputStream());

            System.out.println("File slize : " + fileSize);


            FileOutputStream fout = new FileOutputStream("C:\\Users\\zamalek\\Desktop\\" + fileName);
            int BUFFER_SIZE = 10240;
            byte data[] = new byte[BUFFER_SIZE];
            int count = 0;
            int totalDownloaded = 0;

            long downloadStartTime = System.currentTimeMillis();
            long remainingTime = 0;



            while ((count = in.read(data, 0, BUFFER_SIZE)) != -1) {

                totalDownloaded += count;
                long elapsedTime = System.currentTimeMillis() - downloadStartTime;

                float speedInBytes = 1000f * totalDownloaded / elapsedTime;
                float tmpSpeed = speedInBytes;
                if (tmpSpeed > 1024) {
                    tmpSpeed = tmpSpeed / 1024;
                }
                if (tmpSpeed > 1024 * 1024) {
                    tmpSpeed = tmpSpeed / (1024 * 1024);
                }

                System.out.println("Speed : " + tmpSpeed);

                System.out.println("Remaining Time : " + (fileSize - totalDownloaded) / speedInBytes + " seconds");
                jLabel19.setText((fileSize - totalDownloaded) / speedInBytes + " seconds");
                if (jLabel19.getText().equals("0.0 seconds")) {
                    jLabel17.setText("Complete");
                }
                final int downloadPercentage = (int) ((totalDownloaded / fileSize) );
                Thread thread = new Thread(new Runnable() {
                    @Override
                    public void run() {
                        
                        jProgressBar1.setForeground(Color.RED);

                        int n = 0;
                        int s = 1;
                        while (n <= 100) {
                            try {
                                Thread.sleep(s);
                            } catch (InterruptedException ex) {
                                Logger.getLogger(InternetDownloadManger.class.getName()).log(Level.SEVERE, null, ex);
                            }


                            jProgressBar1.setValue(n);
                            if (n == 80) {


                                jProgressBar1.setForeground(Color.YELLOW);
                                s = 5;
                            } else if (n == 50) {
                                jProgressBar1.setForeground(Color.orange);
                                  
                                s = 2;
                            }
                            n++;

                        }
                    }
                });
                
                
                thread.start();
                
                fout.write(data, 0, count);
                br.write(tmpSpeed + "," + (fileSize - totalDownloaded) / speedInBytes + " seconds" + "," + fileSize + "," + totalDownloaded);
                br.close();

                


            }
                db.getconnection();
                db.AddData(fileName, fileSize+"", U, "C:\\Users\\zamalek\\Desktop\\"+fileName);

        } catch (MalformedURLException ex) {
            System.out.println("er");
            JOptionPane.showMessageDialog(null, " the file source is wrong");
        } catch (IOException ex) {
            System.out.println("er");
             JOptionPane.showMessageDialog(null, "There is no internet connection ");
        } catch (Exception h) {
        }
    }

    public static void downloadFile(String entityID) throws IOException {
        String fileURL = jTextField1.getText();
        entityID = fileURL.substring(fileURL.lastIndexOf("/") + 1);
        String saveDir = "A:\\";
        URL url = new URL(fileURL);
        HttpURLConnection httpConn;// = (HttpURLConnection) url.openConnection();
        int responseCode;// = httpConn.getResponseCode();
        do {
            httpConn = (HttpURLConnection) url.openConnection();
            responseCode = httpConn.getResponseCode();
        } while (responseCode != HttpURLConnection.HTTP_OK);

        // always check HTTP response code first
        if (responseCode == HttpURLConnection.HTTP_OK) {
            System.out.println("Downloading for: " + entityID);
            String fileName = "";
            String disposition = httpConn.getHeaderField("Content-Disposition");

            if (disposition != null) {
                // extracts file name from header field
                int index = disposition.indexOf("filename=");
                if (index > 0) {
                    fileName = disposition.substring(index + 10,
                            disposition.length() - 1);
                }
            } else {
                // extracts file name from URLnhhyyyy
                fileName = fileURL.substring(fileURL.lastIndexOf("/") + 1,
                        fileURL.length());
            }

            // opens input stream from the HTTP connection
            InputStream inputStream = httpConn.getInputStream();
            String saveFilePath = saveDir + File.separator + fileName;

            // opens an output stream to save into file
            //saveFilePath.replace(".rdf", ".txt");
            String downloadAt = saveDir + entityID + ".txt";
            FileOutputStream outputStream = new FileOutputStream(downloadAt);

            int bytesRead = -1;
            byte[] buffer = new byte[4096];
            while ((bytesRead = inputStream.read(buffer)) != -1) {
                outputStream.write(buffer, 0, bytesRead);
            }

            outputStream.close();
            inputStream.close();

            //System.out.println("File downloaded");
        } else {
            System.out.println("Download Failed. Server replied HTTP code: " + responseCode);
        }
        httpConn.disconnect();
    }

    @Override
    public void run() {
    }
}
